In [22]:
import pandas as pd

# Load Data into Pandas DataFrame
train_data = pd.read_csv("./datasets/home-data-for-ml-course/train.csv")
test_data = pd.read_csv("./datasets/home-data-for-ml-course/test.csv")

In [23]:
## Print Columns
train_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [24]:
## Data Deccription
train_data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [25]:
## Sample Data
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [26]:
y = train_data.SalePrice
X = train_data.drop(['SalePrice'],axis=1)

In [27]:
## Find columns with missing values
cols_with_missing = [cname for cname in X.columns if X[cname].isnull().any()]
print("\nColumns with Missing Values:")
print(cols_with_missing)

X.drop(cols_with_missing, inplace=True, axis=1)

print("\nData Frame after dropping missing columns:")
print(X_train_full.columns)

Columns with Missing Values:
['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']

Data Frame after dropping missing columns:
Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [28]:
from sklearn.model_selection import train_test_split

X_train_full,X_valid_full,y_train,y_valid = train_test_split(X,y,train_size=0.8,test_size=0.2)

In [29]:
## Find columns with 
categorical_cols = [cname for cname in X_train_full.columns if (X_train_full[cname].nunique() < 10 and X_train_full[cname].dtype=="object")]
print("\nColumns with Categorical Variables and Low Cardinality:")
print(categorical_cols)

numerical_cols = [cname for cname in X_train_full.columns if X_train_full[cname].dtype in ('int64','float64')]
print("\nColumns with Numerical Variables:")
print(numerical_cols)

feature_cols = categorical_cols + numerical_cols
X_train = X_train_full[feature_cols].copy()
X_valid = X_valid_full[feature_cols].copy()

Columns with Categorical Variables and Low Cardinality:
['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'ExterQual', 'ExterCond', 'Foundation', 'Heating', 'HeatingQC', 'CentralAir', 'KitchenQual', 'Functional', 'PavedDrive', 'SaleType', 'SaleCondition']

Columns with Numerical Variables:
['Id', 'MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

## Initialize Numerical transformer for Simple Impution of Numerical Values
numerical_transformer = SimpleImputer(strategy='constant')

## Initialize Categorical transformer for Object Data Types
categorical_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(transformers=[
    ('num',numerical_transformer,numerical_cols),
    ('cat',categorical_transformer,categorical_cols)
    ])

In [46]:
### Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
DTRmodel = DecisionTreeRegressor(random_state=0)

### Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
RFRmodel = RandomForestRegressor(n_estimators=100,random_state=0)

In [82]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score

def get_cv_score(modelX):
    model_pipeline = Pipeline(steps=[
        ('preprocessor',preprocessor),
        ('model',modelX)
    ])

    scores = -1 * cross_val_score(model_pipeline, X_train, y_train,
                                 cv=5,
                                 scoring='neg_mean_absolute_error')

    print("Mean Absolute Error through %s Cross Validation: %s"%(type(modelX),scores.mean()))
    
def get_score(modelX, **kwargs):
    model_pipeline = Pipeline(steps=[
        ('preprocessing',preprocessor),
        ('model',modelX)
    ])
    
    if kwargs!={}: kwargs = {'model__'+k:v for k,v in enumerate(kwargs)}
    print(kwargs)
    
    ## Fit the training data
    model_pipeline.fit(X_train, y_train, **kwargs)
    ## Predictions for the model
    predictions = model_pipeline.predict(X_valid)  
    ## Find mean absolute error
    mae = mean_absolute_error(predictions, y_valid)
    
    print("Mean Absolute Error: %s"%(mae))

In [83]:
## Using Random Forest Regressor
get_score(RFRmodel)
get_cv_score(RFRmodel)

{}
Mean Absolute Error: 16713.31051369863
Mean Absolute Error through <class 'sklearn.ensemble._forest.RandomForestRegressor'> Cross Validation: 18445.078035068414

In [84]:
## Extreme Gradient Booster
from xgboost import XGBRegressor

XGBmodel = XGBRegressor(n_estimators=1000,learning_rate=0.05,n_jobs=4)

get_score(XGBmodel)
get_score(XGBmodel,early_stopping_rounds=5,eval_set=[(X_valid,y_valid)],verbose=False)
get_cv_score(XGBmodel)

#XGBmodel.fit(X_train, y_train,early_stopping_rounds=5,eval_set=[(X_valid,y_valid)],verbose=False)
#predictions = XGBmodel.predict(X_valid)

{}
Mean Absolute Error: 15565.56524240154

TypeError: must be str, not int

In [81]:
def chow(*args,**kwargs):
    print(args)
    print(kwargs)
    
def ching(y,**kwargs):
    chow(y,**kwargs)
    
chow(5,f=4)
ching(6,g=6)

(5,)
{'f': 4}
(6,)
{'g': 6}